version : '3'
services:
  app:
    container_name: app
    build: .
    depends_on:
      - mysql
    ports:
    - "8080:8080"
    - "9990:9990"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - "./import.sql:/docker-entrypoint-initdb.d/1.sql"