version : '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - "./import.sql:/docker-entrypoint-initdb.d/1.sql"